### ISSUE TITLE
Bug: Issue when adding models to cart

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1007]
How to reproduce:

- Upload multiple files to the service. 
- Select a number of parts, not all.
- Select Shapeways (or other provider)
- See following error message:

![image](https://user-images.githubusercontent.com/25741371/54123510-3e742a80-4400-11e9-9dbb-6950619bae17.png)

**Comment by webholics** [comment]
I couldn't reproduce the issue anymore.
