### ISSUE TITLE
CR: Add "x Files added to your cart" to cart modal after new items added to cart

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#1123]
<img width="348" alt="grafik" src="https://user-images.githubusercontent.com/31536819/59278077-a6394c00-8c61-11e9-87a9-91fd00726872.png">

- [ ] Display cart pop-up after animation for a little time
- [ ] Add "x Files added to your cart" on top

**Comment by Dansken** [comment]
@ranzwertig @webholics @dreampulse This ticket is currently in user acceptance test. Last update I received was that it would take approx. one day to do. 
Is it still in development or is there something ready?

**Comment by webholics** [comment]
Hm no its not done yet, "automation" moved it to to user acceptance test, whatever that is :(

**Comment by henry-all3dp** [comment]
When an issue is closed (e.g. bei merging a linked PR or by manually closing it as @Dansken did 5 days ago) the card will be moved to the User acceptancve Test list.
