### ISSUE TITLE
CR: Find way to open automatic intercom messages

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1167]
We need to find a way to display automatic intercom messages sent to our users. 

The only way to open intercom is by actively seeking help. We used to send messages after 30 seconds, these messages are no longer displayed.

**Comment by Dansken** [comment]
@dreampulse Test failed --

I realized that we are not opening the individual messages but are simply showing the entire Intercom messaging system. 

We need to find a solution to show messages the same way as when customers has already interacted with us and can chat directly on the page. 

Expected behavior:
![image](https://user-images.githubusercontent.com/25741371/60596411-425dfb00-9da9-11e9-8fbf-dcf5ad98cdfb.png)

Not wanted: 
![image](https://user-images.githubusercontent.com/25741371/60596461-5dc90600-9da9-11e9-8f4e-a39ed517f166.png)

**Comment by dreampulse** [comment]
Unfortunately this is the only api intercom provides.
@Dansken can you check if the messages really do not appear? Maybe this was only a configuration issue.

Is this change still live? Should I revert it?

**Comment by Dansken** [comment]
@dreampulse the message is shown as the second example and not opened. 

We have found a solution to the issue, but we would like to have the expected behavior. Is it not possible at all?

**Comment by dreampulse** [comment]
Paused until next week
