### ISSUE TITLE
Bug: Duplicate model prices are shown as equal even if the quantity is different

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1284]
How to reproduce: 

- Upload a model

- Duplicate the model

- Change quantity for one of the models only

- Select PLA and select a cheap provider

- In the cart page, change the quantity of one of the models again. 

The price should be the same for both quantities and potentially also show lower prices than actual price.

**Comment by alex-all3dp** [comment]
Seems to be a Backend Bug: https://github.com/all3dp/printing-engine/issues/1511
