### ISSUE TITLE
Bug: Best price boxes and offer list is not breaking correct on small screensizes

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1364]
![image (4)](https://user-images.githubusercontent.com/25741371/64440006-75837a00-d0cb-11e9-8d54-c6783e3c7d4d.png)
![image (3)](https://user-images.githubusercontent.com/25741371/64440007-761c1080-d0cb-11e9-89fb-712f19eac0be.png)

**Comment by dreampulse** [comment]
This here has been added:
![image](https://user-images.githubusercontent.com/307704/65137639-fb77bd00-da09-11e9-9a7a-1de8ddca0dcc.png)

Do you want to have more mobile breakpoints in between?
We have the problem that we can't distinguish between an open or closed sidebar right now.
