### ISSUE TITLE
Cleanup: Sentry issue backlog - We need to find solutions to the most frequent Sentry issues.

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1365]
https://sentry.io/organizations/all3dp-gmbh/issues/?project=193367&query=is%3Aunresolved&sort=freq&statsPeriod=14d

**Comment by alex-all3dp** [comment]
Still seeing a lot of Sentry issues and no referenced PR here. Why is this in "Done" ?

**Comment by Dansken** [comment]
It was discussed. We need to have better logging.

**Comment by alex-all3dp** [comment]
Please document "solutions" in tickets and don't forget to actually close them 😛

**Comment by Dansken** [comment]
As far as I am aware, no solutions were found.

**Comment by alex-all3dp** [comment]
So re-open?
