### ISSUE TITLE
CR: Reintroduce manufacturer Logo's into the application, instead of text links

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1375]
We need to go back to the provider logo's instead of the blue text links. The change did not have the desired effect. 

We should still keep the modal on click etc.

**Comment by dreampulse** [comment]
This ticket is not ready to implement. A simple revert is not possible. The spacings and layout of the OfferCarts has changed. (There is not enough space for that anymore).
I suggest to create a design for that change.
