### ISSUE TITLE
CR: Indicate non-printable models to the user to help point out why quotes show up as not printable.

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1392]
## Problem description

If the user uploads multiple models, only one model may not be printable. However, this will cause all models to be displayed as "not printable".
Variation: Some models have just one provider with offers.

### Solution concept

a) As soon all printing services completed,  we display a warning if a model greatly reduces the number of potential providers. We show a tooltip with an explanation if the user clicks on the icon.

![image](https://user-images.githubusercontent.com/307704/66033542-c68a6080-e507-11e9-9f0b-2f9dd6b529ce.png)

b) As soon all printing services completed, and if a model reduces the number potential providers to zero we show a modal dialog with some explanation texts and the file names of the broken file. By click on ok we'll remove that model.

**Comment by dreampulse** [comment]
Concept required: How should we indicate that?
