### ISSUE TITLE
Display dynamic production times

### ISSUE THREAD

**Issue by alex-all3dp** [all3dp/printing-engine-client#1397]
Use `productionTimeSlow` and `productionTimeFast` values provided with quotes in price response as proposed in https://github.com/all3dp/printing-engine/issues/1397 and implemented in https://github.com/all3dp/printing-engine/issues/1696

**Comment by dreampulse** [comment]
According to Alex, the backend is not ready jet. The quotes will have a `productionTimeFast` and `productionTimeSlow` field. We should start with that if we have something to test with.
