### ISSUE TITLE
Bug: Text on issue icon is wrong

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1447]
![image](https://user-images.githubusercontent.com/25741371/68401052-5b245600-0179-11ea-9a6b-9227096c8abd.png)

It should be "either" instead of "ether"

**Comment by webholics** [comment]
@Dansken what would be the correct text?

**Comment by Dansken** [comment]
@webholics Good morning ;-) 

It's just a schreibfehler. It says "A problem with the file format or the size of the model is **ether** too small or too big to print." It should be **either**
