### ISSUE TITLE
Handle errors in cart page gracefully

### ISSUE THREAD

**Issue by alex-all3dp** [all3dp/printing-engine-client#1464]
In the cart view the user can retrigger cart creation by triggering new price requests via model duplication or quantity changes.
The re-creation of the cart can fail because either a quote becomes unprintable (e.g. an API partner returns an error) or the backend encounters some other unexpected error.

Currently the client displays the standard error modal and the user loses their cart. We should change this behaviour to display an in-page message that something went wrong and possibly allow the user to retry their changes. Most importantly the user should NOT lose their cart but remain in the cart view. 

To consider: Should we reset the cart to the previous state (models/quantity) or leave it in the current state? Maybe disable the Checkout options and only enable retry + quantity change  until the cart can be created successfully? To be discussed

**Comment by alex-all3dp** [comment]
New API version, merged with https://github.com/all3dp/printing-engine/pull/1876, provides "rich" cart response.
Path `/v3/cart/rich`

**Comment by webholics** [comment]
Um hier weitermachen zu können benötig ich noch das Konzept zu globalen Toasts/Notificiations im Printing Client von Vitus.
