### ISSUE TITLE
CR: Wait with reorganizing material cards based on price until the last price fetch has finished

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1500]
In order to not make too big jumps, cards should transition more smoothly when they change places due to lower prices.

We should wait with reorganizing the material cards until we have received the last price request (or until all manufacturers have finished price fetching).

**Comment by webholics** [comment]
@Dansken lets talk about this again, but I don't think a transition will fix the problem. Could make it even worse.

**Comment by ranzwertig** [comment]
we rejected this
