### ISSUE TITLE
Upload trusted partner area

### ISSUE THREAD

**Issue by ranzwertig** [all3dp/printing-engine-client#1523]
New trusted partner bottom area that will include customers and Trustpilot rating.

https://sketch.cloud/s/w7b8E/a/voeqZ3

**Comment by Dansken** [comment]
Truspilot implementation:

https://trstp.lt/hZ0S_uRKp

Snippets:

 <script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js" async></script> 

 <div class="trustpilot-widget" data-locale="en-US" data-template-id="5419b637fa0340045cd0c936" data-businessunit-id="5d41a5208694d9000156aa8a" data-style-height="20px" data-style-width="100%" data-theme="light"> <a href="https://www.trustpilot.com/review/craftcloud3d.com" target="_blank" rel="noopener">Trustpilot</a> </div>

**Comment by Dansken** [comment]
Test note:
The Trustpilot and customer logo area should always be aligned to the bottom of the users screen, no matter what screen size they are having.
