### ISSUE TITLE
Add new printing providers

### ISSUE THREAD

**Issue by alex-all3dp** [all3dp/printing-engine-client#1577]
- [x] Add images for keys: proteus3d, johnsonprototyping, svensson3d
- [x] Add descriptions
- [x] Add vendor origin information

**Comment by alex-all3dp** [comment]
@Dansken please provide provider images in good enough quality as attachments to this ticket :)

Also you can add the description texts and origin information here as a separate comment

**Comment by Dansken** [comment]
Partner information:

Proteus3D: 
Vendor origin: Canada
Description: Proteus 3D is a Canadian 3D printing service offering a wide range of high quality FDM printed materials at very affordable prices. With Proteus 3D you can always expect a high quality product.
Logo:

**Comment by Dansken** [comment]
Svensson 3D:
Vendor origin: Sweden
Description: Svensson3d are located in Sweden and are specialists in everything 3d printing. From producing small simple toys for the kids to massive prototypes or full-blown series production of several thousand parts per month. No matter your project or need, they can take it from a computer model and make reality. 
Logo: 
![Svensson3D logo](https://user-images.githubusercontent.com/25741371/70538013-b1fac200-1b61-11ea-932b-e5753a1bc262.png)

**Comment by Dansken** [comment]
Johnson Prototyping:
Vendor origin: USA
Description: Johnson Prototyping is based out of Texas, USA. Through a wide variety of FDM printed materials they offer high quality 3D printing with a great attention to detail. Johnson Prototyping are available for any project you may have and can offer competitive prices for both small and large order volumes. 
Logo: 
![johnsonprototyping logo](https://user-images.githubusercontent.com/25741371/70538525-8926fc80-1b62-11ea-811d-f51eea04c0ec.png)
