### ISSUE TITLE
CR: Material cards should always be organized left to right

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#1662]
As we currently organize material cards based on their price, the first card is the cheapest, the one below that card is the next cheapest.

In order to make the view more user friendly, we should always organize the material cards from left to right. 

If the user has 10 cards in view then the top 5 materials should be the 5 cheapest materials. 
Below them the next materials should be the 6-10th cheapest materials. 

When the user changes to the next slider view, the same pattern should follow.

**Comment by webholics** [comment]
We decided to not implement this change.
