### ISSUE TITLE
Inform users, that are using IE, that we do not support IE any longer. We would like to invite them back using a different browser.

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#347]

**Comment by dreampulse** [comment]
![image](https://user-images.githubusercontent.com/307704/32333899-491f4182-bfe9-11e7-956e-c8c407e9539a.png)

Tested with ie9

**Comment by Dansken** [comment]
Test result: 
Test failed, IE 11 looks broken, but no message is displayed. 
![ie11](https://user-images.githubusercontent.com/25741371/32446087-14fc7fb0-c308-11e7-9f70-650d61e3710b.png)

**Comment by dreampulse** [comment]
TODO: add ie11

**Comment by jhnns** [comment]
Tested it in my Virtual Machine. IE 11 gets a banner now.
