### ISSUE TITLE
Update React to v16

### ISSUE THREAD

**Issue by jhnns** [all3dp/printing-engine-client#352]
I tried to update to React to v16, but `react-portal` had some  breaking changes which requires little bit more coding. That's why I skipped this update in #351 

There's also an additional warning about a `<button>` in a `<button>`.

**Comment by jhnns** [comment]
I just found out that we will probably also get better error reports in Sentry with React v16 if we use error boundaries:

- https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html
- https://docs.sentry.io/clients/javascript/integrations/react/

**Comment by henry-all3dp** [comment]
@jhnns is this ticket still relevant or already fixed by #587 ?

**Comment by henry-all3dp** [comment]
Solved by #899
