### ISSUE TITLE
List supported file formats in client and whitelist supported file formats

### ISSUE THREAD

**Issue by tanx** [all3dp/printing-engine-client#371]
STL, OBJ, WRL, SKP, Collada (DAE), 3MF, 3DS, IGS, MODEL, 3DM, FBX, PLY, Magics, MGX, X3D, X3DV, STP,STEP, PRT and MATPART

**Comment by Dansken** [comment]
16pt gray in line under text. 

Change text of "Upload .STL File..." to "Drag any 3D file(s) here or select files"
