### ISSUE TITLE
Sentry: Add source-map to sentry

### ISSUE THREAD

**Issue by dreampulse** [all3dp/printing-engine-client#375]
For some reason sentry does not use the source map.
Checkout the sentry docs to add these.

https://sentry.io/all3dp-gmbh/printing-engine-client/issues/397339935/

**Comment by jhnns** [comment]
Following this guide: https://docs.sentry.io/clients/javascript/sourcemaps/

I think we should upload our source maps to sentry when a release is deployed (using sentry's release feature). There is also a webpack plugin that automates that for us: https://github.com/40thieves/webpack-sentry-plugin

This is their troubleshooting checklist

### General advices
- [ ] *Verify your source maps are built correctly*: The recommended [source map validator](http://sourcemaps.io/report/1510070477679_https%3A%2F%2Fprint.all3dp.com%2Fbundle.js) detects 5 errors and 95 warnings. The errors and warnings are not located in our modules and I'd suspect webpack (or one of its dependencies) as cause. I don't think that these a severe issues, but we need to take a closer look if we have no other option.
- [x] *Verify sourceMappingURL is present*: The URL is present, CloudFlare does not strip it
- [x] *Verify your source maps work locally*: We use the in development, so they work locally, although there might be minor column mapping issues. But I don't expect severe ones.

### Requires Sentry releases
- [ ] *Verify you have specified the release in your client config*
- [x] *Verify artifact names match sourceMappingURL*
- [x] *Verify your source files are not too large (>40MB)*: Our source map is currently 6.3MB. We should code split our application before we hit that limit
- [x] *Verify artifacts are not gzipped*
- [ ] *Verify artifacts are uploaded before errors occur*
