### ISSUE TITLE
Support payment free order request as feature toggle

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#381]
Needed to allow https://github.com/all3dp/printing-engine/issues/328

**Comment by dreampulse** [comment]
Use this query parameters:
http://localhost:3000/?feature:invoice&invoice_key=geheimeschnitzelparty

**Comment by dreampulse** [comment]
https://print.all3dp.com?feature:invoice&invoice_key=rovbanan-schnitzel-party
