### ISSUE TITLE
As a user, I would like to know what the material is the equivalent of at my usual provider. [3SP]

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#400]
See designs in invision: https://projects.invisionapp.com/d/main/default/#/console/9792811/265387399/preview

We need to add a tooltip to the Provider overview, stating the actual name of the material at the provider. This information should also be included in the "learn more" link on the material card.

[3 Storypoints]

**Comment by dreampulse** [comment]
Split prices: Shipping Price, and production price
