### ISSUE TITLE
BUG: Unexpected error message during address input

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#415]

**Comment by henry-all3dp** [comment]
![grafik](https://user-images.githubusercontent.com/31536819/33375797-622bc4d4-d50b-11e7-827b-2e18180d912b.png)

**Comment by dreampulse** [comment]
@jhnns hast du eine Idee woran das liegen könnte? Wir haben ja da erst vor kurzem was geändert
