### ISSUE TITLE
Implement and integrate the new slider into the existing client [5 SP]

### ISSUE THREAD

**Issue by dreampulse** [all3dp/printing-engine-client#419]
![image](https://user-images.githubusercontent.com/307704/33424044-ec034344-d5ba-11e7-9b8f-ab025eb91084.png)

## Notes
- On a click on the arrows a whole page should be slided not just one card
- You are allowed to change the ui if it makes the implementation more easy
- I dos't matter if its an infinite scroll or not

## Tasks

- [x] Implement the Slider-UI in Storybook
- [x] Integrate the new slider into the existing material-container

### Screens
https://projects.invisionapp.com/d/main#/console/9792811/265493182/preview

### Estimated complexity
5 Storypoints

**Comment by webholics** [comment]
Recap: needed 3 storypoints
