### ISSUE TITLE
Form validation to check that first and last name are not longer than 20 characters each

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#477]
Needed to support https://github.com/all3dp/printing-engine/issues/408

**Comment by tanx** [comment]
We also need to check if `(user.shippingAddress.street user.shippingAddress.houseNumber).length <= 80` because sculpteo order will fails othewise.

**Comment by henry-all3dp** [comment]
Was closed in favor of https://github.com/all3dp/printing-engine-client/issues/475
