### ISSUE TITLE
MM: Refactor features to its own reducer/state

### ISSUE THREAD

**Issue by webholics** [all3dp/printing-engine-client#602]
We decided to refactor features into its own reducer and state and its own selector.

There should be an initFeatures actions triggered with the global init() action which then extracts active features from the URL query string and stores it into its own state.

We do not store the features anywhere else or persist the feature query string like we did before.

Also we want to get rid of the `getFeatures` HOC which will then be replaced by a simple selector like we select any other state.

**Comment by jhnns** [comment]
Todo: Discuss if feature toggle should stay in the URL
