### ISSUE TITLE
CRs for multi material client

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#746]
**OVERALL**
- [x] Do not focus on current section but start from top (e.g. material selection, cart page, ...)
- [x] Add 'Upload' and 'Cart' button to all modals (address, checkout) as on the pages (upload, cart, ...)
- [x] Footer: 'Contact us' shall open intercom

**UPLOAD PAGE**
- [x] Display placeholder image for thumbnail while fetching (e.g. a gray image with text 'rendering preview' -> Mikkel will provide file)
- [x] Make entire upload area clickable (click will trigger 'select file')

**MATERIAL MODAL**
- [x] When user still has unconfigured models a click on 'Add to cart' shall redirect the user to the upload page and not the cart. The user will only be redirected to the cart page when all models are configured. 
<img width="1222" alt="grafik" src="https://user-images.githubusercontent.com/31536819/44531280-b2631580-a6f0-11e8-8d11-39914d34f208.png">

**CART PAGE**
- [x] 'Choose material' button in top box shall send user back to upload page with the remaining model(s) selected (see screenshot)
<img width="1154" alt="grafik" src="https://user-images.githubusercontent.com/31536819/44531163-5e583100-a6f0-11e8-8285-862cf9317aa5.png">

- [x] Clicking on 'delete' button of a model shall redirect user to cart page when it was not the last model. If it was the last model, redirect user to upload page.
- [x] Clicking on 'duplicate' button of a model shall redirect customer to upload page with the non-configured model pre-selected.

**ADDRESS MODAL**
- [x] Move email and phone field up above shipping address
- [x] Change country modal: Change the headline to '⚠️ Warning: Lost configuration', make 'cancel' a button and 'ok' normal text

**CART / CHECKOUT BOX**
- [x] Total price just bold and not bigger font size
- [x] On cart page, change 'Go to checkout' to 'Go to:'
- [x] On checkout page, change 'go to checkout' to 'Pay with:'

**CHECKOUT PAGE**
- [x] 'Contact us' and 'Get in touch' shall trigger intercom
- [ ] Show 'edit' button under billing address even when no billing address provided. A click on this edit button will open the address modal with the billig address checkbox checked.
- [x] Name of material should be displayed instead of manufacturing process on the model view. (Keep manufacturing method there in the same font size as the color).
![image](https://user-images.githubusercontent.com/25741371/44663599-53174500-aa11-11e8-9714-42abbb8a4dfb.png)

**SUCCESS PAGE**
- [x] Change headline to 'Thank you for your order with All3DP!'
- [x] Change 'Should you have any questions regarding your order<br>Email us on support@all3dp.com' to 'Questions regarding your order?<br>Email us at support@all3dp.com'

**Comment by webholics** [comment]
I will check the checkmarks when the PR is opened. Just to avoid confusion.

**Comment by webholics** [comment]
Please check  "'Contact us' and 'Get in touch' shall trigger intercom" again because they should already trigger intercom.

**Comment by Dansken** [comment]
![loading_3d_rendering](https://user-images.githubusercontent.com/25741371/44589027-a9894700-a7b7-11e8-84df-94ffca2f8f45.png)
Image for placeholder while rendering the model thumbnail
