### ISSUE TITLE
CR's for after launch:

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#780]
- [x] Change the label of the "Change country" modal to just "Warning". 
![image 10](https://user-images.githubusercontent.com/25741371/45036076-c2b5b180-b05b-11e8-885d-bf47e425b32b.png)

- [x] Finish information is missing from the "Cart" view. Add the finish information with a comma after the material information. 
![image](https://user-images.githubusercontent.com/25741371/45036156-ff81a880-b05b-11e8-8f9b-cd92df531fb0.png)

- [x] If only one provider is selected throughout the order, only show "Shipping" instead of "Shipping - {provider name}
![image 12](https://user-images.githubusercontent.com/25741371/45036215-35269180-b05c-11e8-9331-c3424c1c9730.png)

- [x] Change the model thumbnail to the new and improved "Loading preview" image. 
![loading_preview](https://user-images.githubusercontent.com/25741371/45040491-660bc400-b066-11e8-8d6d-4c112fd2c5d2.png)

- [x] Always pre-select allmodels on upload page - When pressing "Select material" and closing the overlay, the models that were just selected are now de-selected. 

- [ ] Add tooltips to all action buttons.

- [x] replace x/y with x of y where number of selected models is presented.

**Comment by webholics** [comment]
all tasks done expect Tooltips, I'm waiting for texts here.
