### ISSUE TITLE
Add info modal before deleting an object from cart

### ISSUE THREAD

**Issue by henry-all3dp** [all3dp/printing-engine-client#847]
Prompt user with warning before deleting item from cart (similar to country change).

**Comment by Dansken** [comment]
![image](https://user-images.githubusercontent.com/25741371/68863615-05f3c180-06f0-11ea-97ca-415f78ad3db1.png)

**Comment by Dansken** [comment]
In he headline, the text should be:
"Please confirm"

The bold text should read:
"You are about to delete XXX models"

The paragraph text should read:
"The models will be deleted and their configuration will be lost"

**Comment by Dansken** [comment]
@ranzwertig 

Please make a single model delete which has model and not models in the text as well as the last text should be:

"The model will be deleted and its configuration will be lost"
