### ISSUE TITLE
Improved error logging: Improve error logging for paypal and stripe related issues

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#871]
![paypal issue](https://user-images.githubusercontent.com/25741371/47001526-f2f87180-d12a-11e8-8d04-2da570285096.png)

As we currently have a hard time localizing issues in regards to Paypal and Stripe, it would be good to improve our error logging when we have issues in the client related to payment services.

**Comment by henry-all3dp** [comment]
Might be related to https://github.com/all3dp/printing-engine/issues/194
