### ISSUE TITLE
Change request: As a user, I would like to see the finish/color connected to the total price on the material card.

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#884]
We are currently just showing finishes/colors in the way they are structured in the material tree. Unfortunately, this means that sometimes the price on the material card is very different than the price on the finish card. 

Example: 
Standard resin Total Price: $20.00 USD
Standard resin, white: Total price: $25.00 USD

The reason is that white color is the first color in the material tree but the cheapest color is somewhere else in the color options.
![example](https://user-images.githubusercontent.com/25741371/47304868-23a74200-d628-11e8-90fb-9a327e96d609.png)

Change request: Add prices to Finish/color drop down for easier comparison of prices.

**Comment by henry-all3dp** [comment]
Resolved with #888
