### ISSUE TITLE
As a user, I would like to be able to scale my model

### ISSUE THREAD

**Issue by Dansken** [all3dp/printing-engine-client#894]
We have a group of users who have been requesting a scaling feature on our service. 

Using MakePrintable, we need to implement a working feature according to the designs.
![02_cc-upload](https://user-images.githubusercontent.com/25741371/66905514-4a634300-f006-11e9-8e9b-af0ae88204cb.jpg)
![05_cc-upload](https://user-images.githubusercontent.com/25741371/66905515-4a634300-f006-11e9-9560-58e1af123cf8.jpg)

**Comment by dreampulse** [comment]
@Dansken in discussion with @alex-all3dp we should first think about the handling of the backend before we start implementing the frontend.

**Comment by dreampulse** [comment]
TODO: API-Spec required

**Comment by alex-all3dp** [comment]
Issue for API spec: https://github.com/all3dp/printing-engine/issues/1821

**Comment by ranzwertig** [comment]
@Dansken there is a draft PR which is currently blocked by the backend. The scale feature needs to be implemented there first.

**Comment by ranzwertig** [comment]
@Dansken this is implemented in the frontend but we are waiting for a feature in the backend https://github.com/all3dp/printing-engine-client/pull/1493. It can be tested with the current backend.
